services:
  queroplaces:
    image: ${DOCKER_REGISTRY-}queroplaces
    build:
      context: .
      dockerfile: QueroPlaces/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=queroplacedb;Username=postgres;Password=root
      - ConnectionStrings__Redis=redis:6379
      - Elasticsearch__Url=http://elasticsearch:9200
      - Elasticsearch__IndexName=addresses
    ports:
      - "8080:8080"
    networks:
      - queroplace-network

  postgres:
    image: postgis/postgis:13-3.1
    container_name: queroplacedb-postgres
    environment:
      POSTGRES_DB: queroplacedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    networks:
      - queroplace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d queroplacedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: queroplacedb-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - queroplace-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis para cache
  redis:
    image: redis:6.2-alpine
    container_name: queroplacedb-redis
    ports:
      - "6379:6379"
    networks:
      - queroplace-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    container_name: kibana
    image: kibana:8.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - queroplace-network
    

networks:
  queroplace-network:
    driver: bridge

volumes:
  postgres-data:
  elasticsearch-data:
  redis-data: